theme: jekyll-theme-modernist

Here are some simple links for this assignemnt:

[Google Homepage](https://www.google.com "Google's Homepage") 

[GitHub Webpage Code CheatSheet](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)

<figure class="video_container">
  <iframe src="https://www.youtube.com/watch?v=jiXmXhwgHp8&feature=youtu.be" frameborder="0" allowfullscreen="true"> </iframe>
</figure>

Thanks!

AS
