theme: jekyll-theme-modernist

Here are some simple links for this assignemnt:

[Google Homepage](https://www.google.com "Google's Homepage") 

[GitHub Webpage Code CheatSheet](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)

Thanks!

AS
