theme: jekyll-theme-modernist

Here are some simple links for this assignemnt:

[Google Homepage](https://www.google.com "Google's Homepage") 

[GitHub Webpage Code CheatSheet](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)

<div class="videoTag">
<iframe width="560" height="315" src="https://www.youtube.com/embed/jZvC7NWkeA0" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen="" class="ng-scope"></iframe>
</div>
.videoTag{
-webkit-overflow-scrolling: touch;
}

Thanks!

AS
